name: C/C++ CI

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: apt
      run: apt install libssl-dev libevent-dev libnet-dev libpcap-dev libz-dev -y
    - name: make
      run: make
    - name: make install
      run: make install

